plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.2'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'net.mysterria'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

	// Environment Variables
	implementation 'me.paulschwarz:spring-dotenv:4.0.0'

	// Database
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'com.h2database:h2' // For development
	implementation 'org.liquibase:liquibase-core'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// MapStruct
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// OpenAPI/Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

	// Monitoring
	implementation 'io.micrometer:micrometer-registry-prometheus'

	// Utils
	implementation 'org.apache.commons:commons-lang3:3.18.0'
	implementation 'com.google.guava:guava:33.0.0-jre'

	// Markdown Processing
	implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'

	    // JSON Processing
	    implementation 'com.google.code.gson:gson:2.10.1'
		implementation 'io.hypersistence:hypersistence-utils-hibernate-62:3.8.1'

	// Discord Bot
	implementation 'net.dv8tion:JDA:5.0.0-beta.24'

	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.testcontainers:testcontainers'
	testImplementation 'org.testcontainers:postgresql'
	testImplementation 'org.testcontainers:junit-jupiter'
}

bootRun {
	args = ["--spring.profiles.active=development"]
}

tasks.named('test') {
	useJUnitPlatform()
}

springBoot {
	buildInfo()
}